---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    app: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: scottylorraine/addressbook:5.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: addressbook
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8081
  selector:
    app: addressbook
